### ISSUE TITLE
Using pkg.author for homepage causes build error

### ISSUE THREAD

**Issue by jacobq** [unindented/electron-installer-redhat#48]
**What version of `electron-installer-redhat` are you using?**
0.3.1

**What version of `node` and `npm` are you using?**
```
$ node -v; npm -v
v6.10.0
3.10.10
```

**What operating system are you using?**
```
$ uname -a
Linux fractal 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
```

**Can you compile the [example app](https://github.com/unindented/electron-installer-redhat/tree/master/example) successfully?**

Yes, `poopie@0.0.1` builds just fine.

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**

In my application the `author` field is a string of the form `First Last <email@example.com>`, [which is legal syntax](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) yet causes `electron-installer-redhat` to encounter an error since it attempts to use this field as the `homepage` field of the RPM spec.

If you change the example's package.json to use `"author": "John Smith <jsmith@example.com>"` you can see the same problem. Looking at the source code, it appears that there is some regex that assumes that if an author field having type string is present then it must contain a URL surrounded by parenthesis, which it would extract. However, this assumption is not safe, as discussed above, so [this code](https://github.com/unindented/electron-installer-redhat/blob/787306fb3b449f549bd1efb13622f6e2c9fe1d83/src/installer.js#L119) causes the SPEC file to contain a line of the form: `URL: First Last <somebody@example.com>` which is not allowed (field should be a valid URL and not contain spaces).

**What did you expect to happen?**
I expected the `homepage` field to be left blank since I did not specify one. 

**What actually happened?**
The author name and email (package.json author string) were injected into the RPM SPEC causing it to be invalid. An error message like the one below was output at the CLI:

```
Error: Error executing command (1): 
rpmbuild -bb /tmp/electron-11726-5468-117hhuu.lmqbw6d2t9/ember-electron-update-test_0.0.0_x86_64/SPECS/ember-electron-update-test.spec --target x86_64
error: line 5: Tag takes single token only: URL: Author Name <email@example.com>

    at ChildProcess.<anonymous> (/path/to/app/node_modules/electron-installer-redhat/src/installer.js:58:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by jacobq** [comment]
I just noticed that this may be covered by https://github.com/unindented/electron-installer-redhat/pull/45 -- wish I would've seen that before spending 20 minutes digging into this problem to find the culprit.
